---
name: govulncheck
on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']
    paths:
      - go.sum
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
